# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.srcs/sources_1/ip/full_buffer/full_buffer.xci
# IP: The module: 'full_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.srcs/sources_1/ip/full_buffer/full_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'full_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.srcs/sources_1/ip/full_buffer/full_buffer.xci
# IP: The module: 'full_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.srcs/sources_1/ip/full_buffer/full_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'full_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
