# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: X:/Documents/EC551/EC551_Project/Sources/Constraints/Nexys-4-DDR-Master.xdc

# IP: X:/Documents/EC551/EC551_Project/Sources/IP/full_buffer/full_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_buffer || ORIG_REF_NAME==full_buffer} -quiet] -quiet
