webtalk_init -webtalk_dir /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.sim/sim_1/behav/xsim/xsim.dir/test_mem_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov  1 01:39:28 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211078688_174135686_206649660_409" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "61835efa-6569-442e-ba2e-dddbe073e23a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "db26566f0bd64358905dc01a5fbff5e3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "32" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2593.906 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4944796 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "34.79_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131896_KB" -context "xsim\\usage"
webtalk_transmit -clientid 560269253 -regid "211078688_174135686_206649660_409" -xml /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.sim/sim_1/behav/xsim/xsim.dir/test_mem_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.sim/sim_1/behav/xsim/xsim.dir/test_mem_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Project/frame_buffer/frame_buffer.sim/sim_1/behav/xsim/xsim.dir/test_mem_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
