# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: X:/Documents/EC551/EC551_Project/Sources/IP/partial_buffer/partial_buffer.xci
# IP: The module: 'partial_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/Documents/EC551/EC551_Project/Sources/IP/partial_buffer/partial_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'partial_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: X:/Documents/EC551/EC551_Project/Sources/IP/partial_buffer/partial_buffer.xci
# IP: The module: 'partial_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: x:/Documents/EC551/EC551_Project/Sources/IP/partial_buffer/partial_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'partial_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
