# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/wkrska/Downloads/Local Labs/EC551_Project/Sources/IP/full_buffer/full_buffer.xci
# IP: The module: 'full_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wkrska/Downloads/Local Labs/EC551_Project/Sources/IP/full_buffer/full_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'full_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/wkrska/Downloads/Local Labs/EC551_Project/Sources/IP/full_buffer/full_buffer.xci
# IP: The module: 'full_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wkrska/Downloads/Local Labs/EC551_Project/Sources/IP/full_buffer/full_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'full_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
